// AUTO-GENERATED — do not edit by hand.
// Regenerate with: PGPORT=5433 python3 scripts/gen-db-types.py
// Source of truth is supabase/migrations/*.sql.
//
// Relationships are emitted only for the tables listed in EMBEDDED_TABLES in
// the generator — see the comment there for why emitting them everywhere
// breaks type inference.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          id: number;
          organization_id: string | null;
          branch_id: string | null;
          actor_id: string | null;
          actor_label: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          before: Json | null;
          after: Json | null;
          ip: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          organization_id?: string | null;
          branch_id?: string | null;
          actor_id?: string | null;
          actor_label?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          organization_id?: string | null;
          branch_id?: string | null;
          actor_id?: string | null;
          actor_label?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          ip?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      branches: {
        Row: {
          id: string;
          organization_id: string;
          slug: string;
          name: string;
          address: string | null;
          phone: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          slug: string;
          name: string;
          address?: string | null;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          slug?: string;
          name?: string;
          address?: string | null;
          phone?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      branding_settings: {
        Row: {
          organization_id: string;
          logo_url: string | null;
          display_name: string | null;
          primary_color: string;
          secondary_color: string;
          phone: string | null;
          whatsapp: string | null;
          email: string | null;
          white_label: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          organization_id: string;
          logo_url?: string | null;
          display_name?: string | null;
          primary_color?: string;
          secondary_color?: string;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          white_label?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          organization_id?: string;
          logo_url?: string | null;
          display_name?: string | null;
          primary_color?: string;
          secondary_color?: string;
          phone?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          white_label?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      customer_addresses: {
        Row: {
          id: string;
          organization_id: string;
          customer_id: string;
          label: string;
          recipient_name: string | null;
          phone: string | null;
          city: string | null;
          area: string | null;
          address: string;
          landmark: string | null;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          customer_id: string;
          label: string;
          recipient_name?: string | null;
          phone?: string | null;
          city?: string | null;
          area?: string | null;
          address: string;
          landmark?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          customer_id?: string;
          label?: string;
          recipient_name?: string | null;
          phone?: string | null;
          city?: string | null;
          area?: string | null;
          address?: string;
          landmark?: string | null;
          is_default?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      customers: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          name: string;
          phone: string | null;
          email: string | null;
          tax_id: string | null;
          address: string | null;
          notes: string | null;
          user_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          deleted_at: string | null;
          marketing_opt_in: boolean;
          order_updates_opt_in: boolean;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          name: string;
          phone?: string | null;
          email?: string | null;
          tax_id?: string | null;
          address?: string | null;
          notes?: string | null;
          user_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          deleted_at?: string | null;
          marketing_opt_in?: boolean;
          order_updates_opt_in?: boolean;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          name?: string;
          phone?: string | null;
          email?: string | null;
          tax_id?: string | null;
          address?: string | null;
          notes?: string | null;
          user_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          deleted_at?: string | null;
          marketing_opt_in?: boolean;
          order_updates_opt_in?: boolean;
        };
        Relationships: [];
      };
      document_counters: {
        Row: {
          organization_id: string;
          branch_id: string;
          doc_type: string;
          prefix: string;
          next_number: number;
        };
        Insert: {
          organization_id: string;
          branch_id: string;
          doc_type: string;
          prefix?: string;
          next_number?: number;
        };
        Update: {
          organization_id?: string;
          branch_id?: string;
          doc_type?: string;
          prefix?: string;
          next_number?: number;
        };
        Relationships: [];
      };
      invitations: {
        Row: {
          id: string;
          organization_id: string;
          email: string;
          token_hash: string;
          role_ids: string[];
          branch_ids: string[];
          all_branches: boolean;
          invited_by: string;
          expires_at: string;
          accepted_at: string | null;
          revoked_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          email: string;
          token_hash: string;
          role_ids?: string[];
          branch_ids?: string[];
          all_branches?: boolean;
          invited_by: string;
          expires_at: string;
          accepted_at?: string | null;
          revoked_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          email?: string;
          token_hash?: string;
          role_ids?: string[];
          branch_ids?: string[];
          all_branches?: boolean;
          invited_by?: string;
          expires_at?: string;
          accepted_at?: string | null;
          revoked_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      invoice_items: {
        Row: {
          id: string;
          invoice_id: string;
          organization_id: string;
          ref_type: string | null;
          ref_id: string | null;
          description: string;
          quantity: number;
          unit_price_cents: number;
          discount_cents: number;
          tax_rate_bp: number;
          total_cents: number;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          invoice_id: string;
          organization_id: string;
          ref_type?: string | null;
          ref_id?: string | null;
          description: string;
          quantity: number;
          unit_price_cents: number;
          discount_cents?: number;
          tax_rate_bp?: number;
          total_cents: number;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          invoice_id?: string;
          organization_id?: string;
          ref_type?: string | null;
          ref_id?: string | null;
          description?: string;
          quantity?: number;
          unit_price_cents?: number;
          discount_cents?: number;
          tax_rate_bp?: number;
          total_cents?: number;
          position?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      invoices: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          number: string;
          customer_id: string | null;
          status: string;
          source: string;
          currency: string;
          subtotal_cents: number;
          discount_cents: number;
          tax_cents: number;
          total_cents: number;
          paid_cents: number;
          notes: string | null;
          issued_at: string | null;
          due_at: string | null;
          voided_at: string | null;
          void_reason: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          number: string;
          customer_id?: string | null;
          status?: string;
          source?: string;
          currency: string;
          subtotal_cents?: number;
          discount_cents?: number;
          tax_cents?: number;
          total_cents?: number;
          paid_cents?: number;
          notes?: string | null;
          issued_at?: string | null;
          due_at?: string | null;
          voided_at?: string | null;
          void_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          number?: string;
          customer_id?: string | null;
          status?: string;
          source?: string;
          currency?: string;
          subtotal_cents?: number;
          discount_cents?: number;
          tax_cents?: number;
          total_cents?: number;
          paid_cents?: number;
          notes?: string | null;
          issued_at?: string | null;
          due_at?: string | null;
          voided_at?: string | null;
          void_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      member_branches: {
        Row: {
          member_id: string;
          branch_id: string;
          created_at: string;
        };
        Insert: {
          member_id: string;
          branch_id: string;
          created_at?: string;
        };
        Update: {
          member_id?: string;
          branch_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          user_id: string | null;
          recipient: string | null;
          channel: string;
          template: string;
          payload: Json;
          status: string;
          attempts: number;
          last_error: string | null;
          scheduled_for: string;
          sent_at: string | null;
          read_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          user_id?: string | null;
          recipient?: string | null;
          channel: string;
          template: string;
          payload?: Json;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          scheduled_for?: string;
          sent_at?: string | null;
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          user_id?: string | null;
          recipient?: string | null;
          channel?: string;
          template?: string;
          payload?: Json;
          status?: string;
          attempts?: number;
          last_error?: string | null;
          scheduled_for?: string;
          sent_at?: string | null;
          read_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      organization_members: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          status: string;
          all_branches: boolean;
          invited_by: string | null;
          invited_at: string | null;
          joined_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          status?: string;
          all_branches?: boolean;
          invited_by?: string | null;
          invited_at?: string | null;
          joined_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          status?: string;
          all_branches?: boolean;
          invited_by?: string | null;
          invited_at?: string | null;
          joined_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          { foreignKeyName: "organization_members_invited_by_fkey"; columns: ["invited_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "organization_members_organization_id_fkey"; columns: ["organization_id"]; isOneToOne: false; referencedRelation: "organizations"; referencedColumns: ["id"] },
          { foreignKeyName: "organization_members_user_id_fkey"; columns: ["user_id"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
        ];
      };
      organization_modules: {
        Row: {
          id: string;
          organization_id: string;
          module_key: string;
          is_primary: boolean;
          enabled: boolean;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          module_key: string;
          is_primary?: boolean;
          enabled?: boolean;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          module_key?: string;
          is_primary?: boolean;
          enabled?: boolean;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      organizations: {
        Row: {
          id: string;
          slug: string;
          name: string;
          primary_module: string;
          status: string;
          country: string;
          currency: string;
          timezone: string;
          default_locale: string;
          owner_user_id: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          customer_code: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          primary_module: string;
          status?: string;
          country?: string;
          currency?: string;
          timezone?: string;
          default_locale?: string;
          owner_user_id: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          customer_code: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          primary_module?: string;
          status?: string;
          country?: string;
          currency?: string;
          timezone?: string;
          default_locale?: string;
          owner_user_id?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          customer_code?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          invoice_id: string | null;
          customer_id: string | null;
          kind: string;
          method: string;
          amount_cents: number;
          currency: string;
          status: string;
          treasury_account_id: string | null;
          reference: string | null;
          provider: string | null;
          provider_ref: string | null;
          refund_of_id: string | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          invoice_id?: string | null;
          customer_id?: string | null;
          kind?: string;
          method: string;
          amount_cents: number;
          currency: string;
          status?: string;
          treasury_account_id?: string | null;
          reference?: string | null;
          provider?: string | null;
          provider_ref?: string | null;
          refund_of_id?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          invoice_id?: string | null;
          customer_id?: string | null;
          kind?: string;
          method?: string;
          amount_cents?: number;
          currency?: string;
          status?: string;
          treasury_account_id?: string | null;
          reference?: string | null;
          provider?: string | null;
          provider_ref?: string | null;
          refund_of_id?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      permissions: {
        Row: {
          key: string;
          group_key: string;
          module_key: string | null;
          description: string;
          is_elevated: boolean;
          created_at: string;
        };
        Insert: {
          key: string;
          group_key: string;
          module_key?: string | null;
          description: string;
          is_elevated?: boolean;
          created_at?: string;
        };
        Update: {
          key?: string;
          group_key?: string;
          module_key?: string | null;
          description?: string;
          is_elevated?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      plans: {
        Row: {
          id: string;
          key: string;
          name_ar: string;
          name_en: string;
          price_cents: number;
          currency: string;
          interval: string;
          limits: Json;
          features: Json;
          is_public: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          name_ar: string;
          name_en: string;
          price_cents?: number;
          currency?: string;
          interval?: string;
          limits?: Json;
          features?: Json;
          is_public?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          name_ar?: string;
          name_en?: string;
          price_cents?: number;
          currency?: string;
          interval?: string;
          limits?: Json;
          features?: Json;
          is_public?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      platform_admins: {
        Row: {
          user_id: string;
          role: string;
          is_active: boolean;
          note: string | null;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          user_id: string;
          role?: string;
          is_active?: boolean;
          note?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          user_id?: string;
          role?: string;
          is_active?: boolean;
          note?: string | null;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      platform_leads: {
        Row: {
          id: string;
          name: string;
          phone: string;
          business_name: string | null;
          requested_service: string | null;
          source: string;
          status: string;
          notes: string | null;
          organization_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          phone: string;
          business_name?: string | null;
          requested_service?: string | null;
          source?: string;
          status?: string;
          notes?: string | null;
          organization_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          phone?: string;
          business_name?: string | null;
          requested_service?: string | null;
          source?: string;
          status?: string;
          notes?: string | null;
          organization_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      platform_services: {
        Row: {
          module_key: string;
          name_ar: string;
          name_en: string;
          description_ar: string | null;
          is_built: boolean;
          is_available: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          module_key: string;
          name_ar: string;
          name_en: string;
          description_ar?: string | null;
          is_built?: boolean;
          is_available?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          module_key?: string;
          name_ar?: string;
          name_en?: string;
          description_ar?: string | null;
          is_built?: boolean;
          is_available?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          phone: string | null;
          avatar_url: string | null;
          locale: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          locale?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          locale?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      promo_codes: {
        Row: {
          id: string;
          code: string;
          description: string | null;
          kind: string;
          percent_off: number | null;
          amount_off_cents: number | null;
          trial_days: number | null;
          currency: string;
          starts_at: string;
          ends_at: string | null;
          max_redemptions: number | null;
          redeemed_count: number;
          is_active: boolean;
          plan_id: string | null;
          module_key: string | null;
          new_customers_only: boolean;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          code: string;
          description?: string | null;
          kind: string;
          percent_off?: number | null;
          amount_off_cents?: number | null;
          trial_days?: number | null;
          currency?: string;
          starts_at?: string;
          ends_at?: string | null;
          max_redemptions?: number | null;
          redeemed_count?: number;
          is_active?: boolean;
          plan_id?: string | null;
          module_key?: string | null;
          new_customers_only?: boolean;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          code?: string;
          description?: string | null;
          kind?: string;
          percent_off?: number | null;
          amount_off_cents?: number | null;
          trial_days?: number | null;
          currency?: string;
          starts_at?: string;
          ends_at?: string | null;
          max_redemptions?: number | null;
          redeemed_count?: number;
          is_active?: boolean;
          plan_id?: string | null;
          module_key?: string | null;
          new_customers_only?: boolean;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      promo_redemptions: {
        Row: {
          id: number;
          promo_code_id: string;
          organization_id: string;
          subscription_event_id: number | null;
          discount_cents: number;
          trial_days_granted: number;
          redeemed_at: string;
          redeemed_by: string | null;
        };
        Insert: {
          id?: number;
          promo_code_id: string;
          organization_id: string;
          subscription_event_id?: number | null;
          discount_cents?: number;
          trial_days_granted?: number;
          redeemed_at?: string;
          redeemed_by?: string | null;
        };
        Update: {
          id?: number;
          promo_code_id?: string;
          organization_id?: string;
          subscription_event_id?: number | null;
          discount_cents?: number;
          trial_days_granted?: number;
          redeemed_at?: string;
          redeemed_by?: string | null;
        };
        Relationships: [];
      };
      public_links: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          kind: string;
          token: string;
          target: Json;
          label: string | null;
          is_active: boolean;
          expires_at: string | null;
          revoked_at: string | null;
          last_used_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          kind: string;
          token: string;
          target?: Json;
          label?: string | null;
          is_active?: boolean;
          expires_at?: string | null;
          revoked_at?: string | null;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          kind?: string;
          token?: string;
          target?: Json;
          label?: string | null;
          is_active?: boolean;
          expires_at?: string | null;
          revoked_at?: string | null;
          last_used_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      qr_codes: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          public_link_id: string;
          label: string;
          entity_type: string | null;
          entity_id: string | null;
          is_active: boolean;
          printed_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          public_link_id: string;
          label: string;
          entity_type?: string | null;
          entity_id?: string | null;
          is_active?: boolean;
          printed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          public_link_id?: string;
          label?: string;
          entity_type?: string | null;
          entity_id?: string | null;
          is_active?: boolean;
          printed_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      restaurant_branch_availability: {
        Row: {
          organization_id: string;
          branch_id: string;
          variant_id: string;
          is_available: boolean;
          unavailable_note: string | null;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          organization_id: string;
          branch_id: string;
          variant_id: string;
          is_available?: boolean;
          unavailable_note?: string | null;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          organization_id?: string;
          branch_id?: string;
          variant_id?: string;
          is_available?: boolean;
          unavailable_note?: string | null;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [];
      };
      restaurant_categories: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string | null;
          image_url: string | null;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          description?: string | null;
          image_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          description?: string | null;
          image_url?: string | null;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      restaurant_customer_favorites: {
        Row: {
          id: string;
          organization_id: string;
          customer_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          customer_id: string;
          product_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          customer_id?: string;
          product_id?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      restaurant_modifier_groups: {
        Row: {
          id: string;
          organization_id: string;
          product_id: string;
          name: string;
          min_select: number;
          max_select: number;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          product_id: string;
          name: string;
          min_select?: number;
          max_select?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          product_id?: string;
          name?: string;
          min_select?: number;
          max_select?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      restaurant_modifiers: {
        Row: {
          id: string;
          organization_id: string;
          group_id: string;
          name: string;
          price_cents: number;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          group_id: string;
          name: string;
          price_cents?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          group_id?: string;
          name?: string;
          price_cents?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      restaurant_order_deliveries: {
        Row: {
          order_id: string;
          organization_id: string;
          branch_id: string;
          recipient_name: string;
          phone: string;
          city: string | null;
          area: string | null;
          address: string;
          landmark: string | null;
          latitude: number | null;
          longitude: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          order_id: string;
          organization_id: string;
          branch_id: string;
          recipient_name: string;
          phone: string;
          city?: string | null;
          area?: string | null;
          address: string;
          landmark?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          order_id?: string;
          organization_id?: string;
          branch_id?: string;
          recipient_name?: string;
          phone?: string;
          city?: string | null;
          area?: string | null;
          address?: string;
          landmark?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      restaurant_order_item_modifiers: {
        Row: {
          id: string;
          order_item_id: string;
          organization_id: string;
          modifier_id: string | null;
          name: string;
          price_cents: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_item_id: string;
          organization_id: string;
          modifier_id?: string | null;
          name: string;
          price_cents?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_item_id?: string;
          organization_id?: string;
          modifier_id?: string | null;
          name?: string;
          price_cents?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      restaurant_order_items: {
        Row: {
          id: string;
          order_id: string;
          organization_id: string;
          variant_id: string | null;
          product_name: string;
          variant_name: string;
          quantity: number;
          unit_price_cents: number;
          modifiers_cents: number;
          tax_rate_bp: number;
          line_total_cents: number;
          note: string | null;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          organization_id: string;
          variant_id?: string | null;
          product_name: string;
          variant_name?: string;
          quantity: number;
          unit_price_cents: number;
          modifiers_cents?: number;
          tax_rate_bp?: number;
          line_total_cents: number;
          note?: string | null;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          organization_id?: string;
          variant_id?: string | null;
          product_name?: string;
          variant_name?: string;
          quantity?: number;
          unit_price_cents?: number;
          modifiers_cents?: number;
          tax_rate_bp?: number;
          line_total_cents?: number;
          note?: string | null;
          position?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      restaurant_orders: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          table_id: string | null;
          number: string;
          channel: string;
          type: string;
          status: string;
          customer_id: string | null;
          guest_name: string | null;
          guest_phone: string | null;
          note: string | null;
          currency: string;
          subtotal_cents: number;
          discount_cents: number;
          tax_cents: number;
          total_cents: number;
          invoice_id: string | null;
          placed_at: string;
          confirmed_at: string | null;
          ready_at: string | null;
          served_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          cancel_reason: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          customer_edit_until: string | null;
          delivery_fee_cents: number;
          idempotency_key: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          table_id?: string | null;
          number: string;
          channel?: string;
          type?: string;
          status?: string;
          customer_id?: string | null;
          guest_name?: string | null;
          guest_phone?: string | null;
          note?: string | null;
          currency: string;
          subtotal_cents?: number;
          discount_cents?: number;
          tax_cents?: number;
          total_cents?: number;
          invoice_id?: string | null;
          placed_at?: string;
          confirmed_at?: string | null;
          ready_at?: string | null;
          served_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          customer_edit_until?: string | null;
          delivery_fee_cents?: number;
          idempotency_key?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          table_id?: string | null;
          number?: string;
          channel?: string;
          type?: string;
          status?: string;
          customer_id?: string | null;
          guest_name?: string | null;
          guest_phone?: string | null;
          note?: string | null;
          currency?: string;
          subtotal_cents?: number;
          discount_cents?: number;
          tax_cents?: number;
          total_cents?: number;
          invoice_id?: string | null;
          placed_at?: string;
          confirmed_at?: string | null;
          ready_at?: string | null;
          served_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          customer_edit_until?: string | null;
          delivery_fee_cents?: number;
          idempotency_key?: string | null;
        };
        Relationships: [];
      };
      restaurant_products: {
        Row: {
          id: string;
          organization_id: string;
          category_id: string | null;
          name: string;
          description: string | null;
          image_url: string | null;
          tax_rate_bp: number;
          prep_minutes: number;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          category_id?: string | null;
          name: string;
          description?: string | null;
          image_url?: string | null;
          tax_rate_bp?: number;
          prep_minutes?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          category_id?: string | null;
          name?: string;
          description?: string | null;
          image_url?: string | null;
          tax_rate_bp?: number;
          prep_minutes?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      restaurant_sections: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          name: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          name: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          name?: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      restaurant_tables: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          section_id: string | null;
          name: string;
          seats: number;
          status: string;
          public_link_id: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          section_id?: string | null;
          name: string;
          seats?: number;
          status?: string;
          public_link_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          section_id?: string | null;
          name?: string;
          seats?: number;
          status?: string;
          public_link_id?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      restaurant_variants: {
        Row: {
          id: string;
          organization_id: string;
          product_id: string;
          name: string;
          price_cents: number;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          product_id: string;
          name?: string;
          price_cents: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          product_id?: string;
          name?: string;
          price_cents?: number;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      restaurant_website_domains: {
        Row: {
          id: string;
          organization_id: string;
          hostname: string;
          normalized_hostname: string;
          status: string;
          is_primary: boolean;
          verification_method: string;
          verification_token_hash: string;
          verification_attempted_at: string | null;
          verification_error: string | null;
          verified_at: string | null;
          activated_at: string | null;
          disabled_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          hostname: string;
          normalized_hostname: string;
          status?: string;
          is_primary?: boolean;
          verification_method?: string;
          verification_token_hash: string;
          verification_attempted_at?: string | null;
          verification_error?: string | null;
          verified_at?: string | null;
          activated_at?: string | null;
          disabled_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          hostname?: string;
          normalized_hostname?: string;
          status?: string;
          is_primary?: boolean;
          verification_method?: string;
          verification_token_hash?: string;
          verification_attempted_at?: string | null;
          verification_error?: string | null;
          verified_at?: string | null;
          activated_at?: string | null;
          disabled_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      restaurant_website_revisions: {
        Row: {
          id: string;
          organization_id: string;
          version: number;
          sections: Json;
          theme: Json;
          is_live: boolean;
          published_at: string;
          published_by: string | null;
          note: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          version: number;
          sections: Json;
          theme?: Json;
          is_live?: boolean;
          published_at?: string;
          published_by?: string | null;
          note?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          version?: number;
          sections?: Json;
          theme?: Json;
          is_live?: boolean;
          published_at?: string;
          published_by?: string | null;
          note?: string | null;
        };
        Relationships: [];
      };
      restaurant_website_sections: {
        Row: {
          id: string;
          organization_id: string;
          section_type: string;
          sort_order: number;
          enabled: boolean;
          config: Json;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          section_type: string;
          sort_order?: number;
          enabled?: boolean;
          config?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          section_type?: string;
          sort_order?: number;
          enabled?: boolean;
          config?: Json;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      retail_categories: {
        Row: {
          id: string;
          organization_id: string;
          parent_id: string | null;
          name: string;
          sort_order: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          parent_id?: string | null;
          name: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          parent_id?: string | null;
          name?: string;
          sort_order?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      retail_order_deliveries: {
        Row: {
          order_id: string;
          organization_id: string;
          recipient_name: string;
          phone: string;
          city: string;
          area: string | null;
          address_line: string;
          landmark: string | null;
          created_at: string;
        };
        Insert: {
          order_id: string;
          organization_id: string;
          recipient_name: string;
          phone: string;
          city: string;
          area?: string | null;
          address_line: string;
          landmark?: string | null;
          created_at?: string;
        };
        Update: {
          order_id?: string;
          organization_id?: string;
          recipient_name?: string;
          phone?: string;
          city?: string;
          area?: string | null;
          address_line?: string;
          landmark?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      retail_order_items: {
        Row: {
          id: string;
          organization_id: string;
          order_id: string;
          variant_id: string;
          product_name: string;
          variant_name: string;
          quantity: number;
          unit_price_cents: number;
          tax_rate_bp: number;
          line_total_cents: number;
          tax_total_cents: number;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          order_id: string;
          variant_id: string;
          product_name: string;
          variant_name: string;
          quantity: number;
          unit_price_cents: number;
          tax_rate_bp?: number;
          line_total_cents?: number;
          tax_total_cents?: number;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          order_id?: string;
          variant_id?: string;
          product_name?: string;
          variant_name?: string;
          quantity?: number;
          unit_price_cents?: number;
          tax_rate_bp?: number;
          line_total_cents?: number;
          tax_total_cents?: number;
          position?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      retail_orders: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          number: string;
          channel: string;
          status: string;
          fulfillment_type: string;
          customer_id: string | null;
          contact_name: string;
          contact_phone: string;
          currency: string;
          subtotal_cents: number;
          tax_cents: number;
          delivery_fee_cents: number;
          total_cents: number;
          payment_method: string;
          public_token: string;
          idempotency_key: string | null;
          note: string | null;
          placed_at: string;
          confirmed_at: string | null;
          fulfilled_at: string | null;
          completed_at: string | null;
          cancelled_at: string | null;
          cancel_reason: string | null;
          invoice_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          number: string;
          channel?: string;
          status?: string;
          fulfillment_type: string;
          customer_id?: string | null;
          contact_name: string;
          contact_phone: string;
          currency: string;
          subtotal_cents?: number;
          tax_cents?: number;
          delivery_fee_cents?: number;
          total_cents?: number;
          payment_method?: string;
          public_token: string;
          idempotency_key?: string | null;
          note?: string | null;
          placed_at?: string;
          confirmed_at?: string | null;
          fulfilled_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          number?: string;
          channel?: string;
          status?: string;
          fulfillment_type?: string;
          customer_id?: string | null;
          contact_name?: string;
          contact_phone?: string;
          currency?: string;
          subtotal_cents?: number;
          tax_cents?: number;
          delivery_fee_cents?: number;
          total_cents?: number;
          payment_method?: string;
          public_token?: string;
          idempotency_key?: string | null;
          note?: string | null;
          placed_at?: string;
          confirmed_at?: string | null;
          fulfilled_at?: string | null;
          completed_at?: string | null;
          cancelled_at?: string | null;
          cancel_reason?: string | null;
          invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      retail_products: {
        Row: {
          id: string;
          organization_id: string;
          category_id: string | null;
          name: string;
          description: string | null;
          image_url: string | null;
          unit: string;
          tax_rate_bp: number;
          is_active: boolean;
          is_online: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          category_id?: string | null;
          name: string;
          description?: string | null;
          image_url?: string | null;
          unit?: string;
          tax_rate_bp?: number;
          is_active?: boolean;
          is_online?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          category_id?: string | null;
          name?: string;
          description?: string | null;
          image_url?: string | null;
          unit?: string;
          tax_rate_bp?: number;
          is_active?: boolean;
          is_online?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      retail_purchase_order_items: {
        Row: {
          id: string;
          organization_id: string;
          purchase_order_id: string;
          variant_id: string;
          product_name: string;
          variant_name: string;
          quantity_ordered: number;
          quantity_received: number;
          unit_cost_cents: number;
          line_total_cents: number;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          purchase_order_id: string;
          variant_id: string;
          product_name: string;
          variant_name: string;
          quantity_ordered: number;
          quantity_received?: number;
          unit_cost_cents: number;
          line_total_cents?: number;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          purchase_order_id?: string;
          variant_id?: string;
          product_name?: string;
          variant_name?: string;
          quantity_ordered?: number;
          quantity_received?: number;
          unit_cost_cents?: number;
          line_total_cents?: number;
          position?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      retail_purchase_orders: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          supplier_id: string | null;
          number: string;
          status: string;
          currency: string;
          subtotal_cents: number;
          total_cents: number;
          paid_cents: number;
          expected_at: string | null;
          ordered_at: string | null;
          received_at: string | null;
          cancelled_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          supplier_id?: string | null;
          number: string;
          status?: string;
          currency: string;
          subtotal_cents?: number;
          total_cents?: number;
          paid_cents?: number;
          expected_at?: string | null;
          ordered_at?: string | null;
          received_at?: string | null;
          cancelled_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          supplier_id?: string | null;
          number?: string;
          status?: string;
          currency?: string;
          subtotal_cents?: number;
          total_cents?: number;
          paid_cents?: number;
          expected_at?: string | null;
          ordered_at?: string | null;
          received_at?: string | null;
          cancelled_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [
          { foreignKeyName: "retail_purchase_orders_branch_id_fkey"; columns: ["branch_id"]; isOneToOne: false; referencedRelation: "branches"; referencedColumns: ["id"] },
          { foreignKeyName: "retail_purchase_orders_created_by_fkey"; columns: ["created_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "retail_purchase_orders_organization_id_fkey"; columns: ["organization_id"]; isOneToOne: false; referencedRelation: "organizations"; referencedColumns: ["id"] },
          { foreignKeyName: "retail_purchase_orders_supplier_id_fkey"; columns: ["supplier_id"]; isOneToOne: false; referencedRelation: "retail_suppliers"; referencedColumns: ["id"] },
        ];
      };
      retail_shipments: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          order_id: string;
          provider_id: string | null;
          provider_key: string;
          status: string;
          tracking_code: string | null;
          tracking_url: string | null;
          cost_cents: number;
          currency: string;
          recipient_name: string;
          phone: string;
          city: string;
          address_line: string;
          note: string | null;
          failure_reason: string | null;
          dispatched_at: string | null;
          delivered_at: string | null;
          failed_at: string | null;
          cancelled_at: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          order_id: string;
          provider_id?: string | null;
          provider_key?: string;
          status?: string;
          tracking_code?: string | null;
          tracking_url?: string | null;
          cost_cents?: number;
          currency: string;
          recipient_name: string;
          phone: string;
          city: string;
          address_line: string;
          note?: string | null;
          failure_reason?: string | null;
          dispatched_at?: string | null;
          delivered_at?: string | null;
          failed_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          order_id?: string;
          provider_id?: string | null;
          provider_key?: string;
          status?: string;
          tracking_code?: string | null;
          tracking_url?: string | null;
          cost_cents?: number;
          currency?: string;
          recipient_name?: string;
          phone?: string;
          city?: string;
          address_line?: string;
          note?: string | null;
          failure_reason?: string | null;
          dispatched_at?: string | null;
          delivered_at?: string | null;
          failed_at?: string | null;
          cancelled_at?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      retail_shipping_providers: {
        Row: {
          id: string;
          organization_id: string;
          provider_key: string;
          name: string;
          default_cost_cents: number;
          phone: string | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          provider_key?: string;
          name: string;
          default_cost_cents?: number;
          phone?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          provider_key?: string;
          name?: string;
          default_cost_cents?: number;
          phone?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      retail_stock_levels: {
        Row: {
          organization_id: string;
          branch_id: string;
          variant_id: string;
          quantity: number;
          updated_at: string;
        };
        Insert: {
          organization_id: string;
          branch_id: string;
          variant_id: string;
          quantity?: number;
          updated_at?: string;
        };
        Update: {
          organization_id?: string;
          branch_id?: string;
          variant_id?: string;
          quantity?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      retail_stock_movements: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          variant_id: string;
          quantity_delta: number;
          reason: string;
          ref_type: string | null;
          ref_id: string | null;
          unit_cost_cents: number | null;
          note: string | null;
          occurred_at: string;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          variant_id: string;
          quantity_delta: number;
          reason: string;
          ref_type?: string | null;
          ref_id?: string | null;
          unit_cost_cents?: number | null;
          note?: string | null;
          occurred_at?: string;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          variant_id?: string;
          quantity_delta?: number;
          reason?: string;
          ref_type?: string | null;
          ref_id?: string | null;
          unit_cost_cents?: number | null;
          note?: string | null;
          occurred_at?: string;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      retail_suppliers: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          phone: string | null;
          email: string | null;
          address: string | null;
          tax_id: string | null;
          notes: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          tax_id?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          name?: string;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          tax_id?: string | null;
          notes?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      retail_variants: {
        Row: {
          id: string;
          organization_id: string;
          product_id: string;
          name: string;
          sku: string | null;
          barcode: string | null;
          price_cents: number;
          cost_cents: number;
          options: Json;
          reorder_point: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          product_id: string;
          name?: string;
          sku?: string | null;
          barcode?: string | null;
          price_cents: number;
          cost_cents?: number;
          options?: Json;
          reorder_point?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          product_id?: string;
          name?: string;
          sku?: string | null;
          barcode?: string | null;
          price_cents?: number;
          cost_cents?: number;
          options?: Json;
          reorder_point?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          { foreignKeyName: "retail_variants_organization_id_fkey"; columns: ["organization_id"]; isOneToOne: false; referencedRelation: "organizations"; referencedColumns: ["id"] },
          { foreignKeyName: "retail_variants_product_id_fkey"; columns: ["product_id"]; isOneToOne: false; referencedRelation: "retail_products"; referencedColumns: ["id"] },
        ];
      };
      role_permissions: {
        Row: {
          role_id: string;
          permission_key: string;
          created_at: string;
        };
        Insert: {
          role_id: string;
          permission_key: string;
          created_at?: string;
        };
        Update: {
          role_id?: string;
          permission_key?: string;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "role_permissions_permission_key_fkey"; columns: ["permission_key"]; isOneToOne: false; referencedRelation: "permissions"; referencedColumns: ["key"] },
          { foreignKeyName: "role_permissions_role_id_fkey"; columns: ["role_id"]; isOneToOne: false; referencedRelation: "roles"; referencedColumns: ["id"] },
        ];
      };
      roles: {
        Row: {
          id: string;
          organization_id: string | null;
          key: string;
          name_ar: string;
          name_en: string;
          description: string | null;
          is_system: boolean;
          is_owner: boolean;
          module_key: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id?: string | null;
          key: string;
          name_ar: string;
          name_en: string;
          description?: string | null;
          is_system?: boolean;
          is_owner?: boolean;
          module_key?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string | null;
          key?: string;
          name_ar?: string;
          name_en?: string;
          description?: string | null;
          is_system?: boolean;
          is_owner?: boolean;
          module_key?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      settings: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string | null;
          key: string;
          value: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id?: string | null;
          key: string;
          value: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string | null;
          key?: string;
          value?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      subscription_events: {
        Row: {
          id: number;
          organization_id: string;
          subscription_id: string | null;
          event_type: string;
          plan_id: string | null;
          billing_period: string;
          period_start: string;
          period_end: string;
          gross_cents: number;
          discount_cents: number;
          net_cents: number;
          currency: string;
          payment_method: string;
          promo_code_id: string | null;
          promo_code: string | null;
          note: string | null;
          created_at: string;
          created_by: string | null;
          created_by_label: string | null;
        };
        Insert: {
          id?: number;
          organization_id: string;
          subscription_id?: string | null;
          event_type: string;
          plan_id?: string | null;
          billing_period: string;
          period_start: string;
          period_end: string;
          gross_cents?: number;
          discount_cents?: number;
          net_cents?: number;
          currency?: string;
          payment_method?: string;
          promo_code_id?: string | null;
          promo_code?: string | null;
          note?: string | null;
          created_at?: string;
          created_by?: string | null;
          created_by_label?: string | null;
        };
        Update: {
          id?: number;
          organization_id?: string;
          subscription_id?: string | null;
          event_type?: string;
          plan_id?: string | null;
          billing_period?: string;
          period_start?: string;
          period_end?: string;
          gross_cents?: number;
          discount_cents?: number;
          net_cents?: number;
          currency?: string;
          payment_method?: string;
          promo_code_id?: string | null;
          promo_code?: string | null;
          note?: string | null;
          created_at?: string;
          created_by?: string | null;
          created_by_label?: string | null;
        };
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          organization_id: string;
          plan_id: string;
          status: string;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end: boolean;
          provider: string | null;
          provider_ref: string | null;
          created_at: string;
          updated_at: string;
          billing_period: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          plan_id: string;
          status?: string;
          current_period_start?: string;
          current_period_end: string;
          cancel_at_period_end?: boolean;
          provider?: string | null;
          provider_ref?: string | null;
          created_at?: string;
          updated_at?: string;
          billing_period?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          plan_id?: string;
          status?: string;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end?: boolean;
          provider?: string | null;
          provider_ref?: string | null;
          created_at?: string;
          updated_at?: string;
          billing_period?: string;
        };
        Relationships: [
          { foreignKeyName: "subscriptions_organization_id_fkey"; columns: ["organization_id"]; isOneToOne: true; referencedRelation: "organizations"; referencedColumns: ["id"] },
          { foreignKeyName: "subscriptions_plan_id_fkey"; columns: ["plan_id"]; isOneToOne: false; referencedRelation: "plans"; referencedColumns: ["id"] },
        ];
      };
      treasury_accounts: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          name: string;
          type: string;
          currency: string;
          is_default: boolean;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          name: string;
          type?: string;
          currency: string;
          is_default?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          name?: string;
          type?: string;
          currency?: string;
          is_default?: boolean;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      treasury_transactions: {
        Row: {
          id: string;
          organization_id: string;
          branch_id: string;
          account_id: string;
          direction: string;
          amount_cents: number;
          currency: string;
          category: string;
          reason: string | null;
          ref_type: string | null;
          ref_id: string | null;
          occurred_at: string;
          created_at: string;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          branch_id: string;
          account_id: string;
          direction: string;
          amount_cents: number;
          currency: string;
          category: string;
          reason?: string | null;
          ref_type?: string | null;
          ref_id?: string | null;
          occurred_at?: string;
          created_at?: string;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          branch_id?: string;
          account_id?: string;
          direction?: string;
          amount_cents?: number;
          currency?: string;
          category?: string;
          reason?: string | null;
          ref_type?: string | null;
          ref_id?: string | null;
          occurred_at?: string;
          created_at?: string;
          created_by?: string | null;
        };
        Relationships: [];
      };
      user_roles: {
        Row: {
          id: string;
          member_id: string;
          role_id: string;
          branch_id: string | null;
          granted_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          member_id: string;
          role_id: string;
          branch_id?: string | null;
          granted_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          member_id?: string;
          role_id?: string;
          branch_id?: string | null;
          granted_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          { foreignKeyName: "user_roles_branch_id_fkey"; columns: ["branch_id"]; isOneToOne: false; referencedRelation: "branches"; referencedColumns: ["id"] },
          { foreignKeyName: "user_roles_granted_by_fkey"; columns: ["granted_by"]; isOneToOne: false; referencedRelation: "profiles"; referencedColumns: ["id"] },
          { foreignKeyName: "user_roles_member_id_fkey"; columns: ["member_id"]; isOneToOne: false; referencedRelation: "organization_members"; referencedColumns: ["id"] },
          { foreignKeyName: "user_roles_role_id_fkey"; columns: ["role_id"]; isOneToOne: false; referencedRelation: "roles"; referencedColumns: ["id"] },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      customer_account_profile: { Args: Record<string, unknown>; Returns: Json };
      customer_account_save_profile: { Args: Record<string, unknown>; Returns: Json };
      customer_account_save_settings: { Args: Record<string, unknown>; Returns: Json };
      customer_address_delete: { Args: Record<string, unknown>; Returns: Json };
      customer_address_save: { Args: Record<string, unknown>; Returns: Json };
      customer_addresses_list: { Args: Record<string, unknown>; Returns: Json };
      customer_claim_order: { Args: Record<string, unknown>; Returns: Json };
      customer_favorite_add: { Args: Record<string, unknown>; Returns: Json };
      customer_favorite_remove: { Args: Record<string, unknown>; Returns: Json };
      customer_favorites: { Args: Record<string, unknown>; Returns: Json };
      customer_order_detail: { Args: Record<string, unknown>; Returns: Json };
      customer_order_items: { Args: Record<string, unknown>; Returns: Json };
      customer_orders: { Args: Record<string, unknown>; Returns: Json };
      is_org_slug_available: { Args: Record<string, unknown>; Returns: Json };
      platform_admin_grant: { Args: Record<string, unknown>; Returns: Json };
      platform_admin_list: { Args: Record<string, unknown>; Returns: Json };
      platform_admin_revoke: { Args: Record<string, unknown>; Returns: Json };
      platform_create_workspace: { Args: Record<string, unknown>; Returns: Json };
      platform_customer_audit: { Args: Record<string, unknown>; Returns: Json };
      platform_customer_branches: { Args: Record<string, unknown>; Returns: Json };
      platform_customer_domains: { Args: Record<string, unknown>; Returns: Json };
      platform_customer_modules: { Args: Record<string, unknown>; Returns: Json };
      platform_customer_profile: { Args: Record<string, unknown>; Returns: Json };
      platform_dashboard_stats: { Args: Record<string, unknown>; Returns: Json };
      platform_expiring_subscriptions: { Args: Record<string, unknown>; Returns: Json };
      platform_find_user_by_email: { Args: Record<string, unknown>; Returns: Json };
      platform_onboard_customer: { Args: Record<string, unknown>; Returns: Json };
      platform_quote_renewal: { Args: Record<string, unknown>; Returns: Json };
      platform_recent_activity: { Args: Record<string, unknown>; Returns: Json };
      platform_renew_subscription: { Args: Record<string, unknown>; Returns: Json };
      platform_search_customers: { Args: Record<string, unknown>; Returns: Json };
      provision_workspace: { Args: Record<string, unknown>; Returns: Json };
      resolve_public_link: { Args: Record<string, unknown>; Returns: Json };
      restaurant_create_order: { Args: Record<string, unknown>; Returns: Json };
      restaurant_domain_add: { Args: Record<string, unknown>; Returns: Json };
      restaurant_domain_record_verification: { Args: Record<string, unknown>; Returns: Json };
      restaurant_domain_remove: { Args: Record<string, unknown>; Returns: Json };
      restaurant_domain_resolve: { Args: Record<string, unknown>; Returns: Json };
      restaurant_domain_set_primary: { Args: Record<string, unknown>; Returns: Json };
      restaurant_domain_set_status: { Args: Record<string, unknown>; Returns: Json };
      restaurant_domain_verification_target: { Args: Record<string, unknown>; Returns: Json };
      restaurant_domains_list: { Args: Record<string, unknown>; Returns: Json };
      restaurant_issue_table_link: { Args: Record<string, unknown>; Returns: Json };
      restaurant_online_cancel_order: { Args: Record<string, unknown>; Returns: Json };
      restaurant_online_edit_order: { Args: Record<string, unknown>; Returns: Json };
      restaurant_online_menu: { Args: Record<string, unknown>; Returns: Json };
      restaurant_online_modifiers: { Args: Record<string, unknown>; Returns: Json };
      restaurant_online_order_items: { Args: Record<string, unknown>; Returns: Json };
      restaurant_online_order_status: { Args: Record<string, unknown>; Returns: Json };
      restaurant_online_storefront: { Args: Record<string, unknown>; Returns: Json };
      restaurant_pay_order: { Args: Record<string, unknown>; Returns: Json };
      restaurant_place_online_order: { Args: Record<string, unknown>; Returns: Json };
      restaurant_place_public_order: { Args: Record<string, unknown>; Returns: Json };
      restaurant_price_online_cart: { Args: Record<string, unknown>; Returns: Json };
      restaurant_public_context: { Args: Record<string, unknown>; Returns: Json };
      restaurant_public_menu: { Args: Record<string, unknown>; Returns: Json };
      restaurant_public_order_status: { Args: Record<string, unknown>; Returns: Json };
      restaurant_set_order_status: { Args: Record<string, unknown>; Returns: Json };
      restaurant_website: { Args: Record<string, unknown>; Returns: Json };
      restaurant_website_branches: { Args: Record<string, unknown>; Returns: Json };
      restaurant_website_layout: { Args: Record<string, unknown>; Returns: Json };
      restaurant_website_menu: { Args: Record<string, unknown>; Returns: Json };
      restaurant_website_publish: { Args: Record<string, unknown>; Returns: Json };
      restaurant_website_unpublish: { Args: Record<string, unknown>; Returns: Json };
      retail_create_return: { Args: Record<string, unknown>; Returns: Json };
      retail_create_sale: { Args: Record<string, unknown>; Returns: Json };
      retail_order_cancel: { Args: Record<string, unknown>; Returns: Json };
      retail_order_complete: { Args: Record<string, unknown>; Returns: Json };
      retail_order_lines: { Args: Record<string, unknown>; Returns: Json };
      retail_order_set_status: { Args: Record<string, unknown>; Returns: Json };
      retail_order_status: { Args: Record<string, unknown>; Returns: Json };
      retail_place_order: { Args: Record<string, unknown>; Returns: Json };
      retail_price_cart: { Args: Record<string, unknown>; Returns: Json };
      retail_purchase_cancel: { Args: Record<string, unknown>; Returns: Json };
      retail_purchase_create: { Args: Record<string, unknown>; Returns: Json };
      retail_purchase_pay: { Args: Record<string, unknown>; Returns: Json };
      retail_purchase_receive: { Args: Record<string, unknown>; Returns: Json };
      retail_purchase_submit: { Args: Record<string, unknown>; Returns: Json };
      retail_shipment_create: { Args: Record<string, unknown>; Returns: Json };
      retail_shipment_pay: { Args: Record<string, unknown>; Returns: Json };
      retail_shipment_set_status: { Args: Record<string, unknown>; Returns: Json };
      retail_shipment_set_tracking: { Args: Record<string, unknown>; Returns: Json };
      retail_stock_of: { Args: Record<string, unknown>; Returns: Json };
      retail_store_catalog: { Args: Record<string, unknown>; Returns: Json };
      retail_store_context: { Args: Record<string, unknown>; Returns: Json };
      submit_public_lead: { Args: Record<string, unknown>; Returns: Json };
      treasury_account_balance: { Args: Record<string, unknown>; Returns: Json };
      write_platform_audit: { Args: Record<string, unknown>; Returns: Json };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert'];
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update'];
