-- LocalBasic migration-presence audit — read-only, safe against production.
-- One row per migration with a distinct table/function to check for.
select migration, present from (values
  ('0001', (select to_regclass('public.profiles') is not null)),
  ('0002', (select to_regclass('public.permissions') is not null)),
  ('0003', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='is_member_of'))),
  ('0004', (select to_regclass('public.plans') is not null)),
  ('0005', (select to_regclass('public.customers') is not null)),
  ('0006', (select to_regclass('public.public_links') is not null)),
  ('0009', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='provision_workspace'))),
  ('0011', (select to_regclass('public.retail_categories') is not null)),
  ('0012', (select to_regclass('public.retail_stock_levels') is not null)),
  ('0014', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='retail_create_sale'))),
  ('0015', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='retail_create_return'))),
  ('0016', (select to_regclass('public.restaurant_sections') is not null)),
  ('0017', (select to_regclass('public.restaurant_categories') is not null)),
  ('0018', (select to_regclass('public.restaurant_orders') is not null)),
  ('0021', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='restaurant_build_order_lines'))),
  ('0022', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='restaurant_public_context'))),
  ('0023', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='restaurant_pay_order'))),
  ('0024', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='new_public_token'))),
  ('0025', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='bootstrap_restaurant'))),
  ('0026', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='restaurant_sync_order_totals'))),
  ('0029', (select to_regclass('public.platform_admins') is not null)),
  ('0030', (select to_regclass('public.promo_codes') is not null)),
  ('0031', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='provision_workspace_for'))),
  ('0032', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='platform_quote_renewal'))),
  ('0033', (select to_regclass('public.platform_services') is not null)),
  ('0034', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='platform_onboard_customer'))),
  ('0035', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='write_platform_audit'))),
  ('0036', (select to_regclass('public.restaurant_order_deliveries') is not null)),
  ('0037', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='restaurant_online_branch'))),
  ('0038', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='restaurant_setting_bool'))),
  ('0039', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='check_restaurant_setting'))),
  ('0040', (select to_regclass('public.customer_addresses') is not null)),
  ('0041', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='platform_customer_org'))),
  ('0042', (select to_regclass('public.restaurant_website_sections') is not null)),
  ('0043', (select to_regclass('public.restaurant_website_domains') is not null)),
  ('0044', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='domain_org_by_slug'))),
  ('0045', (select to_regclass('public.retail_purchase_orders') is not null)),
  ('0046', (select to_regclass('public.retail_orders') is not null)),
  ('0047', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='stamp_stock_movement_cost'))),
  ('0048', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='is_platform_owner'))),
  ('0049', (select to_regclass('public.retail_shipping_providers') is not null)),
  ('0050', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='notification_claim_batch'))),
  ('0051', (select to_regclass('public.platform_websites') is not null)),
  ('0052', (select to_regclass('public.retail_stock_transfers') is not null)),
  ('0053', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='role_grantable'))),
  ('0054', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='restaurant_pay_order'))),
  ('0055', (select to_regclass('public.sites') is not null)),
  ('0056', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='check_site_identity'))),
  ('0057', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='check_site_section_content'))),
  ('0058', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='check_site_page_identity'))),
  ('0059', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='check_site_section_content'))),
  ('0060', (select to_regclass('public.site_revisions') is not null)),
  ('0061', (select exists (select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='app' and p.proname='platform_customer_site')))
) as t(migration, present) order by 1;
