import { z } from 'zod';

/**
 * What the browser is allowed to send.
 *
 * Note what is absent: no price, no subtotal, no delivery fee, no total, no
 * deadline. The server reads every one of those from current menu data and
 * branch settings, so there is nothing here worth tampering with.
 */

export const FULFILLMENT_TYPES = ['pickup', 'delivery'] as const;
export type Fulfillment = (typeof FULFILLMENT_TYPES)[number];

export const FULFILLMENT_LABELS: Record<Fulfillment, string> = {
  pickup: 'استلام من المطعم',
  delivery: 'توصيل',
};

/** Cash on delivery is the only method in D1. The column accepts more. */
export const ONLINE_PAYMENT_METHODS = ['cash_on_delivery'] as const;

export const cartItem = z.object({
  variantId: z.string().uuid(),
  quantity: z.coerce.number().int().min(1).max(99),
  modifierIds: z.array(z.string().uuid()).max(30).default([]),
  note: z.string().trim().max(240).optional().or(z.literal('')),
});
export type CartItem = z.infer<typeof cartItem>;

export const cart = z.array(cartItem).min(1, 'السلة فارغة').max(100);

export const storefront = z.object({
  orgSlug: z.string().trim().min(2).max(64),
  branchSlug: z.string().trim().min(1).max(64),
});

export const quoteInput = storefront.extend({
  items: cart,
  fulfillment: z.enum(FULFILLMENT_TYPES),
});

export const deliveryAddress = z.object({
  recipientName: z.string().trim().max(120).optional().or(z.literal('')),
  phone: z.string().trim().max(32).optional().or(z.literal('')),
  city: z.string().trim().max(120).optional().or(z.literal('')),
  area: z.string().trim().max(120).optional().or(z.literal('')),
  address: z.string().trim().min(4, 'العنوان مطلوب').max(500),
  landmark: z.string().trim().max(240).optional().or(z.literal('')),
  latitude: z.coerce.number().min(-90).max(90).optional(),
  longitude: z.coerce.number().min(-180).max(180).optional(),
  notes: z.string().trim().max(500).optional().or(z.literal('')),
});

export const checkoutInput = storefront
  .extend({
    items: cart,
    fulfillment: z.enum(FULFILLMENT_TYPES),
    customerName: z.string().trim().min(2, 'الاسم مطلوب').max(120),
    customerPhone: z.string().trim().min(6, 'رقم الهاتف مطلوب').max(32),
    note: z.string().trim().max(500).optional().or(z.literal('')),
    address: deliveryAddress.optional(),
    // D3: names one of the caller's OWN saved addresses. It is not trusted as
    // an address — the server reads the row under the caller's customer id and
    // ignores whatever the form claimed the address said.
    savedAddressId: z.string().uuid().optional(),
    // Generated by the client per checkout attempt, so a retry of the SAME
    // attempt is recognised. It is only a deduplication handle: it grants
    // nothing and is not a capability.
    idempotencyKey: z.string().trim().min(8).max(64),
  })
  .refine(
    (v) => v.fulfillment !== 'delivery' || v.address != null || v.savedAddressId != null,
    { message: 'التوصيل يحتاج عنوانًا', path: ['address'] },
  );

/** The guest's capability token: opaque, 22–64 base64url characters. */
export const orderToken = z
  .string()
  .trim()
  .regex(/^[A-Za-z0-9_-]{22,64}$/, 'رمز غير صالح');

export const editInput = z.object({ token: orderToken, items: cart });
export const cancelInput = z.object({
  token: orderToken,
  reason: z.string().trim().max(240).optional().or(z.literal('')),
});
